### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by timea-techgirl** [SpriggsySpriggs/Appx-Package-Uninstaller#2]
New installed apps or changes done in windows apps aren't detected, old packages are shown or new apps aren't shown
I have to delete the two hidden files apps.txt and appslist.ps1 to fix this

Solution:
Delete these two files automatically on program exit or recreate these files each time program opens

Regards

**Comment by SpriggsySpriggs** [comment]
I made this program a very long time ago so it had very little thought put into it. I can always revamp it sometime

**Comment by timea-techgirl** [comment]
Oh, trust me, it's an amazing tool, very nifty, helped me a lot.
Thanks for the tool. :)

**Comment by SpriggsySpriggs** [comment]
@timea-techgirl I have updated my code to fix the issue you have described. No more files being used

**Comment by SpriggsySpriggs** [comment]
That's very weird..... It works fine on my computer

**Comment by timea-techgirl** [comment]
Yes, when I click uninstall, it opens the powershell window and closes, no commands are run, hence not uninstalled

**Comment by SpriggsySpriggs** [comment]
Never mind. It appears there is an issue with the command working with some apps and not others. Let me check

**Comment by SpriggsySpriggs** [comment]
Apparently it was a matter of the caret `^` character. PowerShell usually requires it when I write code and there is no telling when you don't need it. Apparently this time it didn't like the caret being used as an escape character.

Previous line:
`Shell _Hide "PowerShell -NoProfile -ExecutionPolicy Bypass -Command " + Chr$(34) + "& {Start-Process PowerShell -ArgumentList 'Get-AppxPackage " + appName$ + " ^| Remove-AppxPackage'}" + Chr$(34)`

Current line:
`Shell _Hide "PowerShell -NoProfile -ExecutionPolicy Bypass -Command " + Chr$(34) + "& {Start-Process PowerShell -ArgumentList 'Get-AppxPackage " + appName$ + " | Remove-AppxPackage'}" + Chr$(34)`

**Comment by timea-techgirl** [comment]
Oh I see
I've come across such small changes making commands not work

**Comment by SpriggsySpriggs** [comment]
Is this working for you now?

**Comment by timea-techgirl** [comment]
Oh, let me download again, I thought you hadn't updated the file yet

**Comment by timea-techgirl** [comment]
It shows some red error text along with some blue ones while uninstalling and the listing remains in the app list
When I uninstall the listing again, same red error text but this time the app removes itself from the list

**Comment by SpriggsySpriggs** [comment]
Ok now it should be a lot better. I got rid of the PowerShell window popup and now provide a message box on success or failure. The updating of the list seems to work better now as well.

**Comment by timea-techgirl** [comment]
Does this remove built-in windows bloat apps that can't be removed normally?

**Comment by SpriggsySpriggs** [comment]
It depends on the app. Some can't be uninstalled through the regular command in PowerShell. For instance, this screenshot shows one that can only be uninstalled through Windows Features. There's probably a PowerShell command I can do for that but I'd have to find it and then adapt the code to handle ones that fail because of it.

![image](https://user-images.githubusercontent.com/10662502/120019718-c7161b80-bfb6-11eb-9ee2-c4c79b88a80e.png)

**Comment by SpriggsySpriggs** [comment]
I made another commit that you don't necessarily need to download but the program will self-elevate and uses the `-AllUsers` flag now
https://github.com/SpriggsySpriggs/Appx-Package-Uninstaller/commit/373882b4ee41005818255fc2549b6cf85e7ea208
